<?php
namespace WEEEOpen\Tarallo\SSRv1;


use WEEEOpen\Tarallo\Server\Feature;

class Localizer {

	// BEGIN GENERATED CODE
	const features = [
		'brand' => 'Brand',
		'model' => 'Model',
		'owner' => 'Owner',
		'sn' => 'Serial number (s/n)',
		'mac' => 'MAC address',
		'type' => 'Type',
		'working' => 'Working',
		'capacity-byte' => 'Capacity',
		'frequency-hertz' => 'Frequency',
		'diameter-mm' => 'Diameter',
		'diagonal-inch' => 'Diagonal',
		'isa' => 'Architecture',
		'color' => 'Color',
		'motherboard-form-factor' => 'Form factor (motherboard)',
		'notes' => 'Notes',
		'agp-sockets-n' => 'AGP',
		'arrival-batch' => 'Arrival batch',
		'capacity-decibyte' => 'Capacity ("decimal" bytes)',
		'cib' => 'CIB',
		'core-n' => 'Cores',
		'cpu-socket' => 'Socket (CPU)',
		'dvi-ports-n' => 'DVI',
		'ethernet-ports-1000m-n' => 'Ethernet (gigabit)',
		'ethernet-ports-100m-n' => 'Ethernet (100M)',
		'ethernet-ports-10base2-bnc-n' => 'Ethernet (10BASE2 BNC)',
		'ethernet-ports-10m-n' => 'Ethernet (10M)',
		'hdd-odd-form-factor' => 'Form factor (HDD/ODD)',
		'ide-ports-n' => 'IDE/ATA',
		'odd-type' => 'ODD capabilities',
		'pcie-power-pin-n' => 'PCI Express power pins',
		'pcie-sockets-n' => 'PCI Express',
		'pci-sockets-n' => 'PCI',
		'power-connector' => 'Power connector',
		'power-idle-watt' => 'Power consumption (idle)',
		'power-rated-watt' => 'Power (rated)',
		'ps2-ports-n' => 'PS/2',
		'psu-ampere' => 'Output current',
		'psu-connector-motherboard' => 'Power connector (motherboard)',
		'psu-volt' => 'Output voltage',
		'ram-type' => 'RAM type',
		'sata-ports-n' => 'SATA',
		'software' => 'Software',
		'usb-ports-n' => 'USB',
		'vga-ports-n' => 'VGA',
		'os-license-code' => 'OS license code',
		'os-license-version' => 'OS license version',
		'power-idle-pfc' => 'PFC (idle)',
		'firewire-ports-n' => 'Firewire',
		'mini-firewire-ports-n' => 'Mini Firewire',
		'serial-ports-n' => 'Serial (DE-9)',
		'parallel-ports-n' => 'Parallel',
		'ram-form-factor' => 'Form factor (RAM)',
		'weight-gram' => 'Weight',
		'spin-rate-rpm' => 'Rotation speed',
		'dms-59-ports-n' => 'DMS-59',
		'check' => 'Needs to be checked',
		'ram-ecc' => 'ECC',
		'other-code' => 'Other code(s)',
		'hdmi-ports-n' => 'HDMI',
		'scsi-sca2-ports-n' => 'SCSI SCA2 (80 pin)',
		'scsi-db68-ports-n' => 'SCSI DB68 (68 pin)',
		'mini-ide-ports-n' => 'Mini IDE',
		'data-erased' => 'Erased',
		'surface-scan' => 'Surface scan',
		'smart-data' => 'S.M.A.R.T. data checked',
		'wireless-receiver' => 'Wireless receiver',
		'rj11-ports-n' => 'RJ11 (modem)',
		'ethernet-ports-10base5-aui-n' => 'Ethernet (10BASE5 AUI)',
		'midi-ports-n' => 'MIDI',
		'mini-jack-ports-n' => 'Mini jack',
		'rca-mono-ports-n' => 'RCA Mono',
		'tv-out-ports-n' => 'TV-out',
		's-video-ports-n' => 'S-Video',
		's-video-7pin-ports-n' => 'S-Video (7 pin)',
		'composite-video-ports-n' => 'Composite video',
		'serial-db25-ports-n' => 'DB-25',
		'isa-sockets-n' => 'ISA',
		'mini-pcie-sockets-n' => 'Mini PCI Express',
		'mini-pci-sockets-n' => 'Mini PCI',
		'brand-reseller' => 'Brand (reseller)',
		'psu-form-factor' => 'Form factor (PSU)',
		'cib-old' => 'CIB (old)',
		'integrated-graphics-brand' => 'Integrated graphics brand',
		'integrated-graphics-model' => 'Integrated graphics model',
		'restrictions' => 'Restrictions',
		'displayport-ports-n' => 'DisplayPort',
		'pci-low-profile' => 'PCI low profile',
		'psu-connector-cpu' => 'Power connector (CPU)',
		'jae-ports-n' => 'JAE (50 pin laptop ODD)',
		'game-ports-n' => 'Game port',
	];
	const featuresEnum = [
		'type/location' => 'Location',
		'type/case' => 'Case',
		'type/motherboard' => 'Motherboard',
		'type/cpu' => 'CPU',
		'type/graphics-card' => 'Graphics card',
		'type/ram' => 'RAM',
		'type/hdd' => 'HDD',
		'type/odd' => 'ODD',
		'type/psu' => 'PSU',
		'type/audio-card' => 'Audio card',
		'type/ethernet-card' => 'Ethernet card',
		'type/monitor' => 'Monitor',
		'type/mouse' => 'Mouse',
		'type/keyboard' => 'Keyboard',
		'type/network-switch' => 'Network switch',
		'type/network-hub' => 'Network hub',
		'type/modem-router' => 'Modem/router',
		'type/fdd' => 'FDD',
		'type/ports-bracket' => 'Bracket with ports',
		'type/other-card' => 'Other internal card',
		'type/fan-controller' => 'Fan controller (rheobus)',
		'type/modem-card' => 'Modem card',
		'type/scsi-card' => 'SCSI card',
		'type/wifi-card' => 'WiFi card',
		'type/bluetooth-card' => 'Bluetooth card',
		'type/external-psu' => 'External PSU',
		'type/zip-drive' => 'ZIP drive',
		'type/printer' => 'Printer',
		'type/scanner' => 'Scanner',
		'type/inventoried-object' => 'Other (with invetory sticker)',
		'type/adapter' => 'Adapter',
		'type/usbhub' => 'USB hub',
		'type/tv-card' => 'TV tuner card',
		'working/no' => 'No',
		'working/yes' => 'Yes',
		'working/maybe' => 'Maybe (unclear)',
		'isa/x86-32' => 'x86 32 bit',
		'isa/x86-64' => 'x86 64 bit',
		'isa/ia-64' => 'IA-64',
		'isa/arm' => 'ARM',
		'color/black' => 'Black',
		'color/white' => 'White',
		'color/green' => 'Green',
		'color/yellow' => 'Yellow',
		'color/red' => 'Red',
		'color/blue' => 'Blue',
		'color/grey' => 'Grey',
		'color/darkgrey' => 'Dark grey',
		'color/lightgrey' => 'Light grey',
		'color/pink' => 'Pink',
		'color/transparent' => 'Transparent',
		'color/brown' => 'Brown',
		'color/orange' => 'Orange',
		'color/violet' => 'Violet',
		'color/sip-brown' => 'SIP brown',
		'color/lightblue' => 'Light blue',
		'color/yellowed' => 'Yellowed',
		'color/transparent-dark' => 'Transparent (dark)',
		'color/golden' => 'Golden',
		'motherboard-form-factor/atx' => 'ATX',
		'motherboard-form-factor/miniatx' => 'Mini ATX (not standard)',
		'motherboard-form-factor/microatx' => 'Micro ATX',
		'motherboard-form-factor/miniitx' => 'Mini ITX',
		'motherboard-form-factor/proprietary' => 'Proprietary (desktop)',
		'motherboard-form-factor/btx' => 'BTX (slots ≤ 7)',
		'motherboard-form-factor/microbtx' => 'Micro BTX (slots ≤ 4)',
		'motherboard-form-factor/nanobtx' => 'Nano BTX (slots ≤ 2)',
		'motherboard-form-factor/picobtx' => 'Pico BTX (slots ≤ 1)',
		'motherboard-form-factor/wtx' => 'WTX',
		'motherboard-form-factor/flexatx' => 'Flex ATX',
		'motherboard-form-factor/proprietary-laptop' => 'Laptop',
		'motherboard-form-factor/eatx' => 'Extended ATX',
		'cpu-socket/other-slot' => 'Other (slot)',
		'cpu-socket/other-socket' => 'Other (socket)',
		'cpu-socket/other-dip' => 'Other (DIP)',
		'cpu-socket/g1' => 'G1',
		'cpu-socket/g2' => 'G2',
		'cpu-socket/socket7' => 'Socket 7',
		'cpu-socket/p' => 'P',
		'cpu-socket/am1' => 'AM1',
		'cpu-socket/am2' => 'AM2',
		'cpu-socket/am2plus' => 'AM2+',
		'cpu-socket/am3' => 'AM3',
		'cpu-socket/am3plus' => 'AM3+',
		'cpu-socket/am4' => 'AM4',
		'cpu-socket/fm1' => 'FM1',
		'cpu-socket/fm2' => 'FM2',
		'cpu-socket/fm2plus' => 'FM2+',
		'cpu-socket/g34' => 'G34',
		'cpu-socket/c32' => 'C32',
		'cpu-socket/g3' => 'G3 (rPGA988A)',
		'cpu-socket/slot1' => 'Slot 1',
		'cpu-socket/socket370' => '370',
		'cpu-socket/socket462a' => '462 (Socket A)',
		'cpu-socket/socket423' => '423',
		'cpu-socket/socket478' => '478 (desktop; mPGA478B)',
		'cpu-socket/socket479a' => '479 (mobile; mPGA478A)',
		'cpu-socket/socket479c' => '479 (mobile; mPGA478C)',
		'cpu-socket/socket479m' => '479 (mobile; socket M)',
		'cpu-socket/socket495' => '495',
		'cpu-socket/socket603' => '603',
		'cpu-socket/socket615' => '615',
		'cpu-socket/socket754' => '754',
		'cpu-socket/socket940' => '940',
		'cpu-socket/socket939' => '939',
		'cpu-socket/lga775' => 'LGA775 (Socket T)',
		'cpu-socket/lga771' => 'LGA771 (Socket J)',
		'cpu-socket/lga1366' => 'LGA1366 (Socket B)',
		'cpu-socket/lga1156' => 'LGA1156 (Socket H1)',
		'cpu-socket/lga1248' => 'LGA1248',
		'cpu-socket/lga1567' => 'LGA1567',
		'cpu-socket/lga1155' => 'LGA1155 (Socket H2)',
		'cpu-socket/lga2011' => 'LGA2011 (Socket R)',
		'cpu-socket/lga1150' => 'LGA1150 (Socket H3)',
		'cpu-socket/lga1151' => 'LGA1151 (Socket H4)',
		'cpu-socket/lga3647' => 'LGA3647',
		'cpu-socket/lga2066' => 'LGA2066',
		'hdd-odd-form-factor/5.25' => '5.25 in.',
		'hdd-odd-form-factor/3.5' => '3.5 in.',
		'hdd-odd-form-factor/2.5-15mm' => '2.5 in. (15 mm thick; uncommon)',
		'hdd-odd-form-factor/2.5-7mm' => '2.5 in. (7 mm thick)',
		'hdd-odd-form-factor/2.5-9.5mm' => '2.5 in. (9.5 mm thick)',
		'hdd-odd-form-factor/m2' => 'M2',
		'hdd-odd-form-factor/m2.2' => 'M2.2',
		'hdd-odd-form-factor/laptop-odd-standard' => 'Laptop ODD (standard)',
		'hdd-odd-form-factor/laptop-odd-slim' => 'Laptop ODD (slimmer; uncommon)',
		'odd-type/cd-r' => 'CD-R',
		'odd-type/cd-rw' => 'CD-RW',
		'odd-type/dvd-r' => 'DVD-R',
		'odd-type/dvd-rw' => 'DVD-RW',
		'odd-type/bd-r' => 'BD-R',
		'odd-type/bd-rw' => 'BD-RW',
		'power-connector/other' => 'Other',
		'power-connector/c13' => 'C13/C14',
		'power-connector/c19' => 'C19/C20',
		'power-connector/barrel' => 'Barrel (standard)',
		'power-connector/miniusb' => 'Mini USB',
		'power-connector/microusb' => 'Micro USB',
		'power-connector/proprietary' => 'Proprietary',
		'power-connector/da-2' => 'Dell DA-2',
		'psu-connector-motherboard/proprietary' => 'Proprietary',
		'psu-connector-motherboard/at' => 'AT',
		'psu-connector-motherboard/atx-20pin' => 'ATX 20 pin',
		'psu-connector-motherboard/atx-24pin' => 'ATX 24 pin',
		'psu-connector-motherboard/atx-24pin-mini' => 'Mini ATX 24 pin',
		'psu-connector-motherboard/atx-20pin-aux' => 'ATX 20 pin + AUX',
		'ram-type/simm' => 'SIMM',
		'ram-type/edo' => 'EDO',
		'ram-type/sdr' => 'SDR',
		'ram-type/ddr' => 'DDR',
		'ram-type/ddr2' => 'DDR2',
		'ram-type/ddr3' => 'DDR3',
		'ram-type/ddr4' => 'DDR4',
		'ram-form-factor/simm' => 'SIMM',
		'ram-form-factor/dimm' => 'DIMM',
		'ram-form-factor/sodimm' => 'SODIMM',
		'ram-form-factor/minidimm' => 'Mini DIMM',
		'ram-form-factor/microdimm' => 'Micro DIMM',
		'ram-form-factor/fbdimm' => 'FB-DIMM',
		'check/missing-data' => 'Missing data',
		'check/wrong-data' => 'Wrong data',
		'check/wrong-location' => 'Wrong location/lost',
		'check/wrong-content' => 'Wrong content',
		'check/missing-content' => 'Missing content',
		'check/wrong-data-and-content' => 'Wrong data and content',
		'check/wrong-location-and-data' => 'Wrong location and data (and content)',
		'ram-ecc/no' => 'No',
		'ram-ecc/yes' => 'Yes',
		'data-erased/yes' => 'Yes️',
		'surface-scan/fail' => 'Failed',
		'surface-scan/pass' => 'Passed',
		'smart-data/fail' => 'Failed',
		'smart-data/old' => 'Old',
		'smart-data/ok' => 'Ok',
		'wireless-receiver/inside' => 'Inside the peripheral',
		'wireless-receiver/near' => 'Near the peripheral',
		'wireless-receiver/missing' => 'Missing',
		'psu-form-factor/atx' => 'ATX',
		'psu-form-factor/cfx' => 'CFX',
		'psu-form-factor/lfx' => 'LFX',
		'psu-form-factor/sfx-lowprofile' => 'SFX Low Profile',
		'psu-form-factor/sfx-topfan' => 'SFX Topfan',
		'psu-form-factor/sfx-topfan-reduceddepth' => 'SFX Topfan reduced depth',
		'psu-form-factor/sfx' => 'SFX',
		'psu-form-factor/sfx-ps3' => 'SFX PS3',
		'psu-form-factor/sfx-l' => 'SFX-L',
		'psu-form-factor/tfx' => 'TFX',
		'psu-form-factor/flexatx' => 'Flex ATX',
		'psu-form-factor/proprietary' => 'Proprietary',
		'psu-form-factor/eps' => 'EPS',
		'restrictions/loan' => 'Loaned (to be returned)',
		'restrictions/in-use' => 'In use',
		'restrictions/bought' => 'Bought',
		'restrictions/training' => 'Training/demonstrations',
		'restrictions/ready' => 'Ready',
		'restrictions/other' => 'Other (cannot be donated)',
		'pci-low-profile/no' => 'No',
		'pci-low-profile/possibile' => 'Possible (no bracket)',
		'pci-low-profile/dual' => 'Yes (both brackets)',
		'pci-low-profile/yes' => 'Yes (low profile only)',
		'psu-connector-cpu/none' => 'None',
		'psu-connector-cpu/4pin' => '4 pin',
		'psu-connector-cpu/6pin-hp' => '6 pin (HP; 1 purple + 1 blue)',
		'psu-connector-cpu/6pin-hp-brown' => '6 pin (HP; 2 brown)',
		'psu-connector-cpu/6pin' => '6 pin (other)',
		'psu-connector-cpu/8pin' => '8 pin',
		'psu-connector-cpu/proprietary' => 'Proprietary',
	];
	// END GENERATED CODE

	/**
	 * @param string $locale E.g. en_US, es, etc...
	 */
	public static function localize(string $locale) {
//		$locale = explode('-', $locale, 2);
//		if(count($locale) === 1) {
//			$locale = $locale[0];
//		} else {
//			$locale = $locale[0] . '_' . strtoupper($locale[1]);
//		}
//
//		$domain = 'tarallo';
//		$directory = __DIR__ . DIRECTORY_SEPARATOR . 'locale';
//
//		// putenv is probably not necessary
//		putenv("LC_ALL=$locale.utf8");
//		setlocale(LC_ALL, "$locale.utf8");
//
//		bindtextdomain($domain, $directory);
//		bind_textdomain_codeset($domain, 'UTF-8');
//		textdomain($domain);
	}

	public static function printableName(Feature $feature): string {
		if(isset(self::features[$feature->name])) {
			return self::features[$feature->name];
		} else {
			return $feature->name;
		}
	}

	public static function printableValue(string $name, string $value): string {
		$lookup = $name . '/' . $value;

		if(isset(self::featuresEnum[$lookup])) {
			return self::featuresEnum[$lookup];
		} else {
			return $value;
		}
	}

	public static function allNames() {
		return self::features;
	}
}
