#!/usr/bin/php
<?php

namespace WEEEOpen\Tarallo;

require __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

if($argc > 1) {
	$prefix = rtrim($argv[1], '\/') . DIRECTORY_SEPARATOR;
	foreach([$prefix, $prefix . 'SSRv1/', $prefix . 'APIv1/'] as $dir) {
		if(!is_dir($dir)) {
			echo "$dir is not a directory";
			exit(1);
		}
	}
} else {
	$prefix = '';
}

define('CACHE_ENABLED', true);
SSRv1\Controller::getDispatcher($prefix . 'SSRv1/router.cache');
APIv1\Controller::getDispatcher($prefix . 'APIv1/router.cache');
